language: php

php:
  - 5.4
  - 5.5

before_script: ./scripts/travis_before_script.sh

env:
  - DB=mysql
  - DB=pgsql

script: phpunit --bootstrap ./tests/bootstrap.php ./tests/AllTests.php

matrix:
  # Until #14398 is fixed, PostgreSQL should not cause entire build to fail
  allow_failures:
    - env: DB=pgsql
